/**
 * Named aliases onto the OpenAPI-generated schema (`./generated/schema.d.ts`,
 * regenerated by `npm run generate:api-types` — see that file's own header
 * and this repo's README). Every request/response shape used anywhere in
 * `src/api/*.ts` or `src/features/**` comes from here, never redeclared by
 * hand — see docs/frontend/state-management.md#type-strategy.
 *
 * Owner: frontend-api-agent. This file only aliases; it must never widen,
 * narrow, or reshape a generated type.
 */

import type { components } from './generated/schema'

type Schemas = components['schemas']

// User Service
export type CreateUserRequest = Schemas['CreateUserRequest']
export type UserResponse = Schemas['UserResponse']
export type UserPreferencesResponse = Schemas['UserPreferencesResponse']
export type UpdateUserPreferencesRequest = Schemas['UpdateUserPreferencesRequest']

// Auth (User Service) — see api/auth.ts
export type LoginRequest = Schemas['LoginRequest']
export type LoginResponse = Schemas['LoginResponse']

// Resume/Profile Service
export type CreateResumeRequest = Schemas['CreateResumeRequest']
export type ResumeResponse = Schemas['ResumeResponse']
export type ResumeProfile = Schemas['ResumeProfile']

// Job Ingestion Service
export type IngestJobUrlRequest = Schemas['IngestJobUrlRequest']
export type JobResponse = Schemas['JobResponse']

// Job Discovery Service
export type CreateJobSourceRequest = Schemas['CreateJobSourceRequest']
export type JobSourceResponse = Schemas['JobSourceResponse']

// Job Matching Service
export type JobMatchResponse = Schemas['JobMatchResponse']
export type ProfileMatchScore = Schemas['ProfileMatchScore']

// Contact Discovery Service
export type ContactResponse = Schemas['ContactResponse']
export type TriggerContactSearchRequest = Schemas['TriggerContactSearchRequest']
export type TriggerContactSearchResponse = Schemas['TriggerContactSearchResponse']

// Outreach Service
export type OutreachResponse = Schemas['OutreachResponse']
export type ApproveOutreachRequest = Schemas['ApproveOutreachRequest']
export type EditOutreachRequest = Schemas['EditOutreachRequest']

// Tracking Service
export type ApplicationResponse = Schemas['ApplicationResponse']
export type UpdateApplicationStatusRequest = Schemas['UpdateApplicationStatusRequest']
export type ApplicationHistoryResponse = Schemas['ApplicationHistoryResponse']

// Shared, locked backend enums (shared/types/enums.py) — the single source
// of truth for every lifecycle status this app renders. See
// src/utils/status.ts for the label/category mapping built on top of these;
// nothing in this app may define a competing status value.
export type ApplicationStatus = Schemas['ApplicationStatus']
export type OutreachStatus = Schemas['OutreachStatus']
export type ResumeStatus = Schemas['ResumeStatus']
export type ContactStatus = Schemas['ContactStatus']
export type ContactType = Schemas['ContactType']
export type JobProcessingStatus = Schemas['JobProcessingStatus']
export type MatchRecommendation = Schemas['MatchRecommendation']
export type OutreachChannel = Schemas['OutreachChannel']
export type RemoteWorkPreference = Schemas['RemoteWorkPreference']
